[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  prettyURLs = true
  trailingSlash = true
  
[[redirects]]
from = "https://www.jaxbucerias.com#menu"
to = "https://www.jaxbucerias.com/menu/"
status = 200