[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  prettyURLs = true
  trailingSlash = true
  
[[redirects]]
from = "https://jaxbucerias.netlify.app#menu"
to = "https://jaxbucerias.netlify.app/menu/"
status = 200